In [2]:
import pandas as pd

# Create a sample DataFrame
data = {
    'A': [[1.234, 2.567, 3.789]],
    'B': [[4.123, 5.456, 6.789]],
    'C': [[7.123, 8.456, 9.789]]
}

df = pd.DataFrame(data)

# Define the number of decimal places to round to
decimal_places = 1  # Change this as needed

# Round all float numbers to the specified number of decimal places
df = df.round(decimal_places)

# Now, the DataFrame 'df' contains all float numbers rounded to 'decimal_places' decimal places
df

A                      B                      C
0  [1.234, 2.567, 3.789]  [4.123, 5.456, 6.789]  [7.123, 8.456, 9.789]

In [6]:
import pandas as pd

# Create a sample DataFrame with arrays containing float numbers
data = {
    'A': [[1.234, 2.567, 3.789], [4.123, 5.456, 6.789]],
    'B': [[7.123, 8.456], [9.789, 10.123, 11.456]]
}

df = pd.DataFrame(data)

# Define the number of decimal places to round to
decimal_places = 2  # Change this as needed

# Define a function to round numbers within an array


def round_array(arr):
    return [round(x, decimal_places) for x in arr]


# Use .applymap with a lambda function to round all numbers in arrays
df = df.applymap(lambda x: round_array(x) if isinstance(
    x, list) else round(x, decimal_places))

# Now, the DataFrame 'df' contains all float numbers rounded to 'decimal_places' decimal places, including those in arrays
df

A                     B
0  [1.23, 2.57, 3.79]          [7.12, 8.46]
1  [4.12, 5.46, 6.79]  [9.79, 10.12, 11.46]

In [1]:
import pandas as pd

# Sample DataFrame with an array column
data = {
    'array_column': [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
}

df = pd.DataFrame(data)

# Create new columns by splitting the arrays
df[['col1', 'col2', 'col3']] = pd.DataFrame(
    df['array_column'].tolist(), index=df.index)

# Drop the original array column if needed
df = df.drop(columns=['array_column'])

# Now, the DataFrame 'df' has three separate columns 'col1', 'col2', and 'col3'
df

col1  col2  col3
0     1     2     3
1     4     5     6
2     7     8     9

In [5]:
import pandas as pd


def split_array_to_columns(grouped_df, array_column_name):
    # Define a function to split the array into three separate columns
    def split_array(row):
        return row[array_column_name][0], row[array_column_name][1], row[array_column_name][2]

    # Apply the split_array function to each group and store the results in new columns
    grouped_df['Column1'], grouped_df['Column2'], grouped_df['Column3'] = zip(
        *grouped_df.apply(split_array, axis=1))

    # Find the maximum and minimum values in the three columns for each group
    max_values = grouped_df.groupby(
        column_name)[['Column1', 'Column2', 'Column3']].max()
    min_values = grouped_df.groupby(
        column_name)[['Column1', 'Column2', 'Column3']].min()

    # Reset the index of the max and min DataFrames
    max_values.reset_index(inplace=True)
    min_values.reset_index(inplace=True)

    # Combine the max and min values side by side
    result = pd.merge(max_values, min_values, on=column_name,
                      suffixes=('_max', '_min'))

    return result


# Example usage:
column_name = 'group_column'
score = 'score_column'

# Create a sample DataFrame
data = {
    column_name: ['A', 'A', 'B', 'B', 'C', 'C'],
    score: [(1, 2, 3), (4, 5, 6), (7, 8, 9),
            (10, 11, 12), (13, 14, 15), (16, 17, 18)]
}

df = pd.DataFrame(data)

# Group by 'group_column' and apply the custom function
result = df.groupby(column_name).apply(
    split_array_to_columns, array_column_name=score)

# Reset the index of the result DataFrame
result.reset_index(drop=True, inplace=True)

# Print the result
print(result)

  group_column  Column1_max  Column2_max  Column3_max  Column1_min  \
0            A            4            5            6            1   
1            B           10           11           12            7   
2            C           16           17           18           13   

   Column2_min  Column3_min  
0            2            3  
1            8            9  
2           14           15  


In [11]:
import pandas as pd

# Create a sample DataFrame with an index column
data = {
    'Original_Index': [100, 101, 102],
    'A': [1, 2, 3],
    'B': [4, 5, 6],
    'C': [7, 8, 9],
    'D': [10, 11, 12],
    'E': [13, 14, 15],
    'F': [16, 17, 18]
}

# Create a DataFrame with an index
df = pd.DataFrame(data)

# Define the new order of columns
new_column_order = ['A', 'D', 'B', 'E', 'C', 'F']

# Reset the index and rename it to 'Index_Column'
df.reset_index(inplace=True)
df.set_index('Original_Index', inplace=True)

# Reorder the columns
df = df[new_column_order]

# Your DataFrame now has the columns in the new order with the index renamed to 'Index_Column'
df

A   D  B   E  C   F
Original_Index                     
100             1  10  4  13  7  16
101             2  11  5  14  8  17
102             3  12  6  15  9  18

In [7]:
import numpy as np
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

random_array = np.random.rand(10, 3)
normalized_array = random_array / random_array.sum(axis=1, keepdims=True)
data_3d = normalized_array
print(data_3d)
mean = np.mean(data_3d, axis=1)
sigma = np.std(data_3d, axis=1)
features = np.column_stack((mean, sigma))
scaler = StandardScaler()
normalized_features = scaler.fit_transform(features)
print(normalized_features)
kmeans = KMeans(n_clusters=3)
cluster_labels = kmeans.fit_predict(normalized_features)

# Print cluster labels
print(cluster_labels)

[[0.20792095 0.33706285 0.4550162 ]
 [0.42122323 0.2368433  0.34193347]
 [0.12792883 0.39692779 0.47514339]
 [0.80380507 0.17848905 0.01770588]
 [0.11163291 0.66436225 0.22400484]
 [0.32421427 0.23433871 0.44144703]
 [0.30246935 0.41537947 0.28215118]
 [0.07604141 0.52489443 0.39906416]
 [0.18502563 0.39822287 0.4167515 ]
 [0.75178488 0.03170695 0.21650817]]
[[-5.55111512e-17 -6.72135340e-01]
 [-5.55111512e-17 -9.40238479e-01]
 [-5.55111512e-17 -1.67439607e-01]
 [-5.55111512e-17  1.84260759e+00]
 [-5.55111512e-17  7.80848425e-01]
 [-5.55111512e-17 -8.42266938e-01]
 [-5.55111512e-17 -1.11880754e+00]
 [-5.55111512e-17  2.58425342e-01]
 [-5.55111512e-17 -6.27461483e-01]
 [-5.55111512e-17  1.48646803e+00]]
[1 1 2 0 2 1 1 2 1 0]


c:\Users\muhammad.aasif\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\cluster\_kmeans.py:1412: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)


In [8]:
import numpy as np
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

# Sample 3D data
data_3d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9],
                   [10, 11, 12]])

# Calculate mean and sigma for each dimension
mean = np.mean(data_3d, axis=0)
sigma = np.std(data_3d, axis=0)

# Create a feature matrix based on mean and sigma
features = np.column_stack((mean, sigma))

# Normalize the feature matrix
scaler = StandardScaler()
normalized_features = scaler.fit_transform(features)
print(normalized_features)
# Apply k-means clustering
kmeans = KMeans(n_clusters=3)
cluster_labels = kmeans.fit_predict(normalized_features)

# Print cluster labels
print(cluster_labels)

[[-1.22474487  0.        ]
 [ 0.          0.        ]
 [ 1.22474487  0.        ]]
[2 0 1]


c:\Users\muhammad.aasif\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\cluster\_kmeans.py:1412: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)


In [9]:
import pandas as pd

# Sample DataFrame
data = {'Sentiments': [[-0.1, 0.2, 0.3],
                       [0.4, -0.5, 0.6],
                       [0.7, 0.8, -0.9]]}

df = pd.DataFrame(data)

# Split the 'Sentiments' column into three separate columns
df[['Negative', 'Neutral', 'Positive']] = df['Sentiments'].apply(pd.Series)

# Drop the original 'Sentiments' column if needed
df = df.drop('Sentiments', axis=1)

# Print the resulting DataFrame
print(df)

   Negative  Neutral  Positive
0      -0.1      0.2       0.3
1       0.4     -0.5       0.6
2       0.7      0.8      -0.9


In [10]:
import pandas as pd

# Create a sample DataFrame
data = {'Column1': [3, 1, 2, 3, 2],
        'Column2': [10, 20, 15, 5, 25]}
df = pd.DataFrame(data)

# Sort the DataFrame first by 'Column1', then by 'Column2'
sorted_df = df.sort_values(by=['Column1', 'Column2'])

print(sorted_df)

   Column1  Column2
1        1       20
2        2       15
4        2       25
3        3        5
0        3       10
